name: 'Get SPDX license overview'
description: 'Get SPDX license overview'
author: "Forest Keepers"
branding:
  icon: "activity"
  color: "green"

outputs:
  spdx-file:
    description: "spdx-license file"
    value: ${{ steps.spdx.outputs.spdx-file }}
  ort-file:
    description: "ort-license file"
    value: ${{ steps.spdx.outputs.ort-file }}

inputs:
  project:
    description: "project"
    required: true
    default: 'spdx-builder'
  spdx-builder-version:
    description: "spdx-builder-version"
    required: true
    default: 'v0.5.0'
  ort-version:
    description: "philipssoftware/ort version"
    required: false
    default: '2021-03-03'
  ort-file:
    description: "Specifies an ort-file to override ORT scanning in this action."
    required: true
  scanner-url:
    description: "scanner-url (license-scanner)"
    required: false
  upload-url:
    description: "upload-url (f.e. BOM-bar)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Scan with ORT 
      run: |
        [ -n "${ORT_FILE}" ] && { echo "We have our own ORT_FILE so we don't need to scan it here"; exit 0; }
        # Allow ORT to fail. When one repository can't be found, the rest still makes sense to analyse 
        echo "--------------------------------------------------------------------"
        echo " Running ORT scanner"
        echo "--------------------------------------------------------------------"
        set +e
        docker run -v ${{ github.workspace }}:/project philipssoftware/ort:${{ inputs.ort-version}} --info analyze -f JSON -i /project -o /project/ort
        set -e
      shell: bash
      env:
        ORT_FILE: ${{ inputs.ort-file }}
    - name: Create SPDX file
      id: spdx
      run: |
        echo "--------------------------------------------------------------------"
        echo " Creating SPDX file for ${PROJECT}. "
        echo "--------------------------------------------------------------------"
        echo " Inputs: "
        echo "    PROJECT              : ${PROJECT} "
        echo "    SCANNER_URL          : ${SCANNER_URL} "
        echo "    UPLOAD_URL           : ${UPLOAD_URL} "
        echo "    ORT_FILE             : ${ORT_FILE} "
        echo "--------------------------------------------------------------------"
        echo ""
        echo "--------------------------------------------------------------------"
        echo " Downloading spdx-builder"
        echo "--------------------------------------------------------------------"
        curl -L https://github.com/philips-software/spdx-builder/releases/download/${{ inputs.spdx-builder-version }}/spdx-builder.jar -o spdx-builder.jar
        echo "--------------------------------------------------------------------"
        echo " Set SCANNER_ARG"
        echo "--------------------------------------------------------------------"
        [ -z "$SCANNER_URL" ] && SCANNER_ARG="" || SCANNER_ARG="--scanner ${SCANNER_URL}"
        echo "          SCANNER_ARG: ${SCANNER_ARG}"
        echo "--------------------------------------------------------------------"
        echo " Set input-file"
        echo "--------------------------------------------------------------------"
        [ -n "$ORT_FILE" ] && INPUT_FILE=${ORT_FILE} || INPUT_FILE="ort/analyzer-result.json"
        echo "          INPUT_FILE: ${INPUT_FILE}"
        echo "--------------------------------------------------------------------"
        echo " Set UPLOAD_ARG"
        echo "--------------------------------------------------------------------"
        [ -z "$UPLOAD_URL" ] && UPLOAD_ARG="" || UPLOAD_ARG="--upload ${UPLOAD_URL}"
        echo "          UPLOAD_ARG: ${UPLOAD_ARG}"
        echo "--------------------------------------------------------------------"
        echo " Running SPDX-builder"
        echo "--------------------------------------------------------------------"
        java -jar spdx-builder.jar ort -c .spdx-builder.yml -o ${PROJECT}.spdx ${INPUT_FILE} ${SCANNER_ARG} ${UPLOAD_ARG}
        echo "--------------------------------------------------------------------"
        echo "Finished!"
        echo "--------------------------------------------------------------------"
        echo "::set-output name=spdx-file::${PROJECT}.spdx"
        echo "::set-output name=ort-file::${INPUT_FILE}"
      env:
        PROJECT: ${{ inputs.project }}
        SCANNER_URL: ${{ inputs.scanner-url }}
        ORT_FILE: ${{ inputs.ort-file }}
        UPLOAD_URL: ${{ inputs.upload-url }}
      shell: bash
